pipeline:
  identifier: Build_miguel_ca_docker_django_webapp_linux_1726799568147
  name: Build docker-django-webapp-linux
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1726794362854
        repoName: miguel-ca/docker-django-webapp-linux
  stages:
    - stage:
        name: Build
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            key: cache-{{ checksum "requirements.txt" }}
            paths:
              - /root/.cache
          execution:
            steps:
              - step:
                  type: Run
                  identifier: dependencies
                  name: Dependencies
                  spec:
                    shell: Sh
                    command: |-
                      python -m pip install --upgrade pip
                      pip install -r requirements.txt
                    envVariables:
                      PIP_CACHE_DIR: /root/.cache
              - step:
                  type: Run
                  name: Test
                  identifier: test
                  spec:
                    shell: Sh
                    command: |-
                      echo hello world
                      echo imagine that I\'m a great test
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - report.xml
                    envVariables:
                      PIP_CACHE_DIR: /root/.cache
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.myaccount
                    repo: ataqueosuno/hi-there/
                    tags:
                      - test
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          sharedPaths:
            - /root/.cache
